### ISSUE TITLE
.exe file

### ISSUE THREAD

**Issue by jayjupdhig** [weegillis/exif-viewer#1]
have an .exe file?

**Comment by weegillis** [comment]
No, it is PHP. The working files are mounted in any images folder(s) (index.php, etc.) The code library is a separate file, as is the template.
This would need to be ported to C++ or Java (or maybe Node.js) to be executed locally. Completely out of my wheelhouse at this stage in time.

**Comment by jayjupdhig** [comment]
Oh...
